[package]
name = "numero"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.7"
rodio = "0.17.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
plotters = "0.3.5"
colorous = "1.0.12"
rustfft = "6.2"
